// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Riskified.NetSDK.Model
{
    public class DiscountCode
    {
        [JsonProperty(PropertyName = "amount", Required = Required.Default)]
        public double MoneyDiscountSum { get; set; }

        [JsonProperty(PropertyName = "code", Required = Required.Default)]
        public string Code { get; set; }
    }

}
