// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Riskified.NetSDK.Model
{
    public class DiscountCode


    {
        public DiscountCode(double? moneyDiscountSum = null, string code = null)
        {
            MoneyDiscountSum = moneyDiscountSum;
            Code = code;
        }

        [JsonProperty(PropertyName = "amount", Required = Required.Default,NullValueHandling = NullValueHandling.Ignore)]
        public double? MoneyDiscountSum { get; set; }

        [JsonProperty(PropertyName = "code", Required = Required.Default,NullValueHandling = NullValueHandling.Ignore)]
        public string Code { get; set; }
    }

}
